#!/bin/sh

# StellarMate Pro MTP Startup Script
modprobe libcomposite

root=/sys/kernel/config
gadget=$root/usb_gadget/g1
strings=$gadget/strings/0x409
configs=$gadget/configs/c.1
functions=$gadget/functions/ffs.mtp

mkdir -p $strings
mkdir -p $configs/strings/0x409
mkdir -p $functions

echo 0x0100 > $gadget/idProduct
echo 0x1D6B > $gadget/idVendor

echo "01234567" > $strings/serialnumber
echo "Ikarus Technologies" > $strings/manufacturer
echo "StellarMate Pro" > $strings/product

echo "Conf 1" > $configs/strings/0x409/configuration
echo 120 > $configs/MaxPower

if [ ! -e "$configs/ffs.mtp" ]
then
   ln -s $functions $configs
fi

if [ ! -e "/dev/ffs-mtp" ];
then
   mkdir /dev/ffs-mtp
   mount -t functionfs mtp /dev/ffs-mtp
fi

