#!/bin/sh

# GadgetFS uMTPrd startup example/test script

# Raspberry Pi : start dwc2 & gadgetfs

modprobe dwc2
modprobe gadgetfs

# Mount gadgetfs

mkdir /dev/gadget || true
mount -t gadgetfs gadgetfs /dev/gadget || true
